name: Build and publish npm package through the repos devcontainer
description: Builds and publishes a npm package to the package registry.

inputs:
  npmAuthToken:
    description: Authentication token for the npm registry.
    required: false
    default: ''
  projectDirectory:
    description: The path to the directory containing the package.json file to build from. Include the relative path from the root of the repository if necessary.
    required: true
  version:
    description: The semantic version to apply such as 1.0.0 or 1.0.0-alpha2+a12b345.
    required: true
  packageRegistry:
    description: The URL of the npm package registry to push to.
    required: false
    default: https://npm.pkg.github.com/${{ github.repository_owner }}/index.json
  registryHost:
    description: The host of the container registry to pull devcontainers from. If not provided, no login will be performed.
    required: false
    default: ''
  registryUsername:
    description: The username to use to authenticate with the container registry for pulling devcontainers. If not provided, no login will be performed.
    required: false
    default: ''
  registryPassword:
    description: The token to use to authenticate with the container registry for pulling devcontainers. If not provided, no login will be performed.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - id: prepare
      name: Prepare devcontainer environment
      shell: bash
      run: |
        mkdir -p ./.devcontainer
        touch ./.devcontainer/.env

        # Need to copy the build script files to a path that will work inside the devcontainer
        # Trying to use a path name that is very unlikely to create a conflict in any user repos
        
        base_dir=".github-actions-publish-npm"
        temp_dir="$base_dir"
        counter=1
        
        # Find a unique directory name
        while [ -e "$temp_dir" ]; do
          temp_dir="${base_dir}-${counter}"
          counter=$((counter + 1))
        done
        
        # Create the directory and copy the script
        mkdir -p "$temp_dir"
        cp "${{ github.action_path }}/publish-npm.sh" "$temp_dir/publish-npm.sh"
        chmod +x "$temp_dir/publish-npm.sh"
        
        echo "Using temporary directory: $temp_dir"
        
        # Set output variables
        echo "publishNPMDirectory=$temp_dir" >> $GITHUB_OUTPUT

    - name: Publish NPM package
      if: github.ref_type == 'branch'
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          source "/src/${{ steps.prepare.outputs.publishNPMDirectory }}/publish-npm.sh"
        push: never
        env: |
          PROJECT_DIRECTORY=${{ inputs.projectDirectory }}
          VERSION=${{ inputs.version }}
          PACKAGE_REGISTRY=${{ inputs.packageRegistry }}
          NODE_AUTH_TOKEN=${{ inputs.npmAuthToken }}

    - name: Remove temporary files
      if: always()
      shell: bash
      run: |
        if [ -d "${{ steps.prepare.outputs.publishNPMDirectory }}" ]; then
          rm -rf "${{ steps.prepare.outputs.publishNPMDirectory }}"
          echo "Removed temporary directory: ${{ steps.prepare.outputs.publishNPMDirectory }}"
        fi
