FROM verdaccio/verdaccio

USER root

RUN npm install --global-style --no-bin-links --no-optional --prefix /tmp/plugin-install @wunderwerk/verdaccio-static-access-token-middleware-plugin \
    && mv /tmp/plugin-install/ /verdaccio/plugins/ \
    && chown -R $VERDACCIO_USER_UID:root /verdaccio/plugins \
    && rm -rf /tmp/plugin-install/
